### ISSUE TITLE
After running Vagrantfile, unable to connect via localhost:5000

### ISSUE THREAD

**Issue by devinodaniel** [morbidick/ansible-role-semaphore#1]
I was able to successfully run the Vagrantfile and provision the ubuntu VM. However, upon attempting to access the site via `localhost:5000` or `127.0.0.1:5000` the connection is refused.

Also tried `localhost:3000` or `127.0.0.1:3000` just in case.

I'm able to `vagrant ssh` into the box and can verify that all the components are installed and when I run `/opt/semaphore/semaphore --config /etc/semaphore/semaphore.json` the output is:

    Semaphore 2.3.0
    Port :3000
    MySQL semaphore@127.0.0.1:3306 semaphore
    Tmp Path (projects home) /opt/semaphore/tmp

**Comment by devinodaniel** [comment]
Okay, it hasn't worked for hours and for some reason its working now as soon as I post this. (Of course) But it's on port 3000 instead of 5000. May want to update readme to reflect this instead of `127.0.0.1:5000`.

**Comment by morbidick** [comment]
Oh yeah, i updated the readme, thank you for reporting.
