### ISSUE TITLE
Fails to install on CentOS 8

### ISSUE THREAD

**Issue by JaySeeJC** [morbidick/ansible-role-semaphore#6]
Fails to install with the following error:

`TASK [morbidick.semaphore : install Python MySQL module] ***********************************************************************************************
fatal: [192.168.70.55]: FAILED! => {"changed": false, "failures": ["No package MySQL-python available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}`

**Comment by morbidick** [comment]
Do you know what the package is called in centos? If you like i would appreciate a PR :)

**Comment by RankoKohime** [comment]
Also failing on Ubuntu 22.04, same package.  This has been renamed to python3-mysqldb in Ubuntu, perhaps likewise in CentOS.

I will dig into this soon, as I don't know if the dependency is for python 2 or 3.

**Comment by RankoKohime** [comment]
It seems line 46 in defaults/main.yml is the culprit.  On Ubuntu 22.04, ansible_python_interpreter is not set, per the facts.

**Comment by morbidick** [comment]
Hi @RankoKohime , 
Thank you for triaging this issue. I'm currently not actively using this role, but I would love to keep it alive. Would you be up for opening a pull request? :)

**Comment by morbidick** [comment]
I adapted to playbook for current CentOs, Ubuntu and Semaphore release, now i only have to get the github action to work :)
