### ISSUE TITLE
Fails to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by good-praxis** [morbidick/ansible-role-semaphore#7]
The role fails to install during the Python MySQL Module phase, trying to install `python-mysqldb` while the package is called `python3-mysqldb`

**Comment by good-praxis** [comment]
Nevermind, I realized this isn't breaking but can be configured in the server's playbook by passing on the `semaphore_python_mysql_module` variable

**Comment by morbidick** [comment]
should work for ubuntu 20.04 out of the box from now on :)
